//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simit.resources.@string {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simit.resources.string.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amazonas.
        /// </summary>
        internal static string amazonas {
            get {
                return ResourceManager.GetString("amazonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Antioquia.
        /// </summary>
        internal static string antioquia {
            get {
                return ResourceManager.GetString("antioquia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AIzaSyAVahCEPXRXG3IGoH8i0n9ORpwe3mxoREI.
        /// </summary>
        internal static string API_KEY_APP_ANDROID {
            get {
                return ResourceManager.GetString("API_KEY_APP_ANDROID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simit.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arauca.
        /// </summary>
        internal static string arauca {
            get {
                return ResourceManager.GetString("arauca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atlántico.
        /// </summary>
        internal static string atlantic {
            get {
                return ResourceManager.GetString("atlantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www2.simit.org.co/simit/menu/menu_inicial.jsp.
        /// </summary>
        internal static string body_email {
            get {
                return ResourceManager.GetString("body_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bogotá D.C..
        /// </summary>
        internal static string bogota_dc {
            get {
                return ResourceManager.GetString("bogota_dc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bolívar.
        /// </summary>
        internal static string bolivar {
            get {
                return ResourceManager.GetString("bolivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boyacá.
        /// </summary>
        internal static string boyaca {
            get {
                return ResourceManager.GetString("boyaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caldas.
        /// </summary>
        internal static string caldas {
            get {
                return ResourceManager.GetString("caldas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caquetá.
        /// </summary>
        internal static string caqueta {
            get {
                return ResourceManager.GetString("caqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CÉDULA VENEZOLANA.
        /// </summary>
        internal static string card_venezuela {
            get {
                return ResourceManager.GetString("card_venezuela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casanare.
        /// </summary>
        internal static string casanare {
            get {
                return ResourceManager.GetString("casanare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cauca.
        /// </summary>
        internal static string cauca {
            get {
                return ResourceManager.GetString("cauca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cesar.
        /// </summary>
        internal static string cesar {
            get {
                return ResourceManager.GetString("cesar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UCoT2mmYn3Bxfpc_TQxZlRnA.
        /// </summary>
        internal static string CHANELID_YOU_TUBE {
            get {
                return ResourceManager.GetString("CHANELID_YOU_TUBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chocó.
        /// </summary>
        internal static string choco {
            get {
                return ResourceManager.GetString("choco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CÉDULA DE CIUDADANÍA.
        /// </summary>
        internal static string citizenship_card {
            get {
                return ResourceManager.GetString("citizenship_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REGISTRO CIVIL.
        /// </summary>
        internal static string civil_registration {
            get {
                return ResourceManager.GetString("civil_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a oyPeJmke0eto8rxZZuOBzrNim.
        /// </summary>
        internal static string Consumer_Key_twitter {
            get {
                return ResourceManager.GetString("Consumer_Key_twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dOh3sS9pNzzhsyPocKFg7Be51l9Q60KvaE1UoTBeK2Q0VEqX02.
        /// </summary>
        internal static string Consumer_Secret_twitter {
            get {
                return ResourceManager.GetString("Consumer_Secret_twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dOh3sS9pNzzhsyPocKFg7Be51l9Q60KvaE1UoTBeK2Q0VEqX02.
        /// </summary>
        internal static string consumer_token_secret_twitter {
            get {
                return ResourceManager.GetString("consumer_token_secret_twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a oyPeJmke0eto8rxZZuOBzrNim.
        /// </summary>
        internal static string consumer_token_twitter {
            get {
                return ResourceManager.GetString("consumer_token_twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Córoba.
        /// </summary>
        internal static string cordoba {
            get {
                return ResourceManager.GetString("cordoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cundinamarca.
        /// </summary>
        internal static string cundinamarca {
            get {
                return ResourceManager.GetString("cundinamarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulte en nuestra app información importante de los organismos de transito..
        /// </summary>
        internal static string dialog_share {
            get {
                return ResourceManager.GetString("dialog_share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CARNET DIPLOMATÍCO.
        /// </summary>
        internal static string diplomatic_passport {
            get {
                return ResourceManager.GetString("diplomatic_passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error y el tweet no fue publicado..
        /// </summary>
        internal static string error_post_tweet {
            get {
                return ResourceManager.GetString("error_post_tweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guainía.
        /// </summary>
        internal static string guainía {
            get {
                return ResourceManager.GetString("guainía", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guaviare.
        /// </summary>
        internal static string guaviare {
            get {
                return ResourceManager.GetString("guaviare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Huila.
        /// </summary>
        internal static string huila {
            get {
                return ResourceManager.GetString("huila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TARJETA DE IDENTIDAD.
        /// </summary>
        internal static string identity_card {
            get {
                return ResourceManager.GetString("identity_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Guajira.
        /// </summary>
        internal static string la_guajira {
            get {
                return ResourceManager.GetString("la_guajira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Magdalena.
        /// </summary>
        internal static string magdalena {
            get {
                return ResourceManager.GetString("magdalena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al recuperar los datos, intente nuevamente..
        /// </summary>
        internal static string MENSAGE_ERROR_LOAD_DATA {
            get {
                return ResourceManager.GetString("MENSAGE_ERROR_LOAD_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se perdió la conexión, verifique su conexión de internet.
        /// </summary>
        internal static string MENSAGE_NOT_CONECTION_INTERNET {
            get {
                return ResourceManager.GetString("MENSAGE_NOT_CONECTION_INTERNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe Ingresar un numero de documento valido..
        /// </summary>
        internal static string MESSAGE_NOT_IMPUT_DATA {
            get {
                return ResourceManager.GetString("MESSAGE_NOT_IMPUT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tweet fue publicado correctamente..
        /// </summary>
        internal static string message_public_tweet_ok {
            get {
                return ResourceManager.GetString("message_public_tweet_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meta.
        /// </summary>
        internal static string meta {
            get {
                return ResourceManager.GetString("meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nariño.
        /// </summary>
        internal static string nariño {
            get {
                return ResourceManager.GetString("nariño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NIT.
        /// </summary>
        internal static string nit {
            get {
                return ResourceManager.GetString("nit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Norte de Santander.
        /// </summary>
        internal static string north_of_santander {
            get {
                return ResourceManager.GetString("north_of_santander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nose pudo obtener los datos, por favor intente nuevamente..
        /// </summary>
        internal static string not_get_data {
            get {
                return ResourceManager.GetString("not_get_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PASAPORTE.
        /// </summary>
        internal static string passport {
            get {
                return ResourceManager.GetString("passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acuerdos de Pago.
        /// </summary>
        internal static string payment_arrangements {
            get {
                return ResourceManager.GetString("payment_arrangements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Putumayo.
        /// </summary>
        internal static string putumayo {
            get {
                return ResourceManager.GetString("putumayo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quindío.
        /// </summary>
        internal static string quindio {
            get {
                return ResourceManager.GetString("quindio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resoluciones.
        /// </summary>
        internal static string resolutions {
            get {
                return ResourceManager.GetString("resolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Risalda.
        /// </summary>
        internal static string risalda {
            get {
                return ResourceManager.GetString("risalda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a San Andrés y Providencia.
        /// </summary>
        internal static string san_andres_providencia {
            get {
                return ResourceManager.GetString("san_andres_providencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Santander.
        /// </summary>
        internal static string santander {
            get {
                return ResourceManager.GetString("santander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comparendos.
        /// </summary>
        internal static string subpoenas {
            get {
                return ResourceManager.GetString("subpoenas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sucre.
        /// </summary>
        internal static string sucre {
            get {
                return ResourceManager.GetString("sucre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El texto debe contener como maximo 140 caracteres..
        /// </summary>
        internal static string text_dialog_twitter {
            get {
                return ResourceManager.GetString("text_dialog_twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tolina.
        /// </summary>
        internal static string tolina {
            get {
                return ResourceManager.GetString("tolina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://es-es.facebook.com/simitnacional.
        /// </summary>
        internal static string url_page_facebook {
            get {
                return ResourceManager.GetString("url_page_facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www.simit.org.co/.
        /// </summary>
        internal static string url_page_simit {
            get {
                return ResourceManager.GetString("url_page_simit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://mobile.twitter.com/Simit_FCM.
        /// </summary>
        internal static string url_page_twitter {
            get {
                return ResourceManager.GetString("url_page_twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www2.simit.org.co.
        /// </summary>
        internal static string url_site_simit {
            get {
                return ResourceManager.GetString("url_site_simit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valle del Cauca.
        /// </summary>
        internal static string valle_del_cauca {
            get {
                return ResourceManager.GetString("valle_del_cauca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vaupés.
        /// </summary>
        internal static string vaupes {
            get {
                return ResourceManager.GetString("vaupes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vichada.
        /// </summary>
        internal static string vichada {
            get {
                return ResourceManager.GetString("vichada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CÉDULA DE EXTRANJERÍA.
        /// </summary>
        internal static string writ_of_estranjeria {
            get {
                return ResourceManager.GetString("writ_of_estranjeria", resourceCulture);
            }
        }
    }
}
