//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace Simit.GetPointsService {
    
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class clsDatosPuntos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string celular1Field;
        
        private string celular2Field;
        
        private string direccionesField;
        
        private string emailField;
        
        private string horariosField;
        
        private string latitudField;
        
        private string longitudField;
        
        private string municipiosField;
        
        private string sectoresField;
        
        private string telefono1Field;
        
        private string telefono2Field;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string celular1 {
            get {
                return this.celular1Field;
            }
            set {
                this.celular1Field = value;
                this.RaisePropertyChanged("celular1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string celular2 {
            get {
                return this.celular2Field;
            }
            set {
                this.celular2Field = value;
                this.RaisePropertyChanged("celular2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direcciones {
            get {
                return this.direccionesField;
            }
            set {
                this.direccionesField = value;
                this.RaisePropertyChanged("direcciones");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string horarios {
            get {
                return this.horariosField;
            }
            set {
                this.horariosField = value;
                this.RaisePropertyChanged("horarios");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
                this.RaisePropertyChanged("latitud");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
                this.RaisePropertyChanged("longitud");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string municipios {
            get {
                return this.municipiosField;
            }
            set {
                this.municipiosField = value;
                this.RaisePropertyChanged("municipios");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string sectores {
            get {
                return this.sectoresField;
            }
            set {
                this.sectoresField = value;
                this.RaisePropertyChanged("sectores");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string telefono1 {
            get {
                return this.telefono1Field;
            }
            set {
                this.telefono1Field = value;
                this.RaisePropertyChanged("telefono1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string telefono2 {
            get {
                return this.telefono2Field;
            }
            set {
                this.telefono2Field = value;
                this.RaisePropertyChanged("telefono2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="GetPointsService.WsPuntosAtencion")]
    public interface WsPuntosAtencion {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://Servicios/WsPuntosAtencion/BuscarPuntosRequest", ReplyAction="http://Servicios/WsPuntosAtencion/BuscarPuntosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Simit.GetPointsService.Exception), Action="http://Servicios/WsPuntosAtencion/BuscarPuntos/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginBuscarPuntos(Simit.GetPointsService.BuscarPuntosRequest request, System.AsyncCallback callback, object asyncState);
        
        Simit.GetPointsService.BuscarPuntosResponse EndBuscarPuntos(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarPuntos", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class BuscarPuntosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodDepartamento;
        
        public BuscarPuntosRequest() {
        }
        
        public BuscarPuntosRequest(string CodDepartamento) {
            this.CodDepartamento = CodDepartamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarPuntosResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class BuscarPuntosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("puntos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Simit.GetPointsService.clsDatosPuntos[] @return;
        
        public BuscarPuntosResponse() {
        }
        
        public BuscarPuntosResponse(Simit.GetPointsService.clsDatosPuntos[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsPuntosAtencionChannel : Simit.GetPointsService.WsPuntosAtencion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BuscarPuntosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public BuscarPuntosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Simit.GetPointsService.clsDatosPuntos[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Simit.GetPointsService.clsDatosPuntos[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsPuntosAtencionClient : System.ServiceModel.ClientBase<Simit.GetPointsService.WsPuntosAtencion>, Simit.GetPointsService.WsPuntosAtencion {
        
        private BeginOperationDelegate onBeginBuscarPuntosDelegate;
        
        private EndOperationDelegate onEndBuscarPuntosDelegate;
        
        private System.Threading.SendOrPostCallback onBuscarPuntosCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WsPuntosAtencionClient() {
        }
        
        public WsPuntosAtencionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsPuntosAtencionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsPuntosAtencionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsPuntosAtencionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<BuscarPuntosCompletedEventArgs> BuscarPuntosCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Simit.GetPointsService.WsPuntosAtencion.BeginBuscarPuntos(Simit.GetPointsService.BuscarPuntosRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBuscarPuntos(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginBuscarPuntos(string CodDepartamento, System.AsyncCallback callback, object asyncState) {
            Simit.GetPointsService.BuscarPuntosRequest inValue = new Simit.GetPointsService.BuscarPuntosRequest();
            inValue.CodDepartamento = CodDepartamento;
            return ((Simit.GetPointsService.WsPuntosAtencion)(this)).BeginBuscarPuntos(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Simit.GetPointsService.BuscarPuntosResponse Simit.GetPointsService.WsPuntosAtencion.EndBuscarPuntos(System.IAsyncResult result) {
            return base.Channel.EndBuscarPuntos(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private Simit.GetPointsService.clsDatosPuntos[] EndBuscarPuntos(System.IAsyncResult result) {
            Simit.GetPointsService.BuscarPuntosResponse retVal = ((Simit.GetPointsService.WsPuntosAtencion)(this)).EndBuscarPuntos(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginBuscarPuntos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string CodDepartamento = ((string)(inValues[0]));
            return this.BeginBuscarPuntos(CodDepartamento, callback, asyncState);
        }
        
        private object[] OnEndBuscarPuntos(System.IAsyncResult result) {
            Simit.GetPointsService.clsDatosPuntos[] retVal = this.EndBuscarPuntos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnBuscarPuntosCompleted(object state) {
            if ((this.BuscarPuntosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BuscarPuntosCompleted(this, new BuscarPuntosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void BuscarPuntosAsync(string CodDepartamento) {
            this.BuscarPuntosAsync(CodDepartamento, null);
        }
        
        public void BuscarPuntosAsync(string CodDepartamento, object userState) {
            if ((this.onBeginBuscarPuntosDelegate == null)) {
                this.onBeginBuscarPuntosDelegate = new BeginOperationDelegate(this.OnBeginBuscarPuntos);
            }
            if ((this.onEndBuscarPuntosDelegate == null)) {
                this.onEndBuscarPuntosDelegate = new EndOperationDelegate(this.OnEndBuscarPuntos);
            }
            if ((this.onBuscarPuntosCompletedDelegate == null)) {
                this.onBuscarPuntosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBuscarPuntosCompleted);
            }
            base.InvokeAsync(this.onBeginBuscarPuntosDelegate, new object[] {
                        CodDepartamento}, this.onEndBuscarPuntosDelegate, this.onBuscarPuntosCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Simit.GetPointsService.WsPuntosAtencion CreateChannel() {
            return new WsPuntosAtencionClientChannel(this);
        }
        
        private class WsPuntosAtencionClientChannel : ChannelBase<Simit.GetPointsService.WsPuntosAtencion>, Simit.GetPointsService.WsPuntosAtencion {
            
            public WsPuntosAtencionClientChannel(System.ServiceModel.ClientBase<Simit.GetPointsService.WsPuntosAtencion> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginBuscarPuntos(Simit.GetPointsService.BuscarPuntosRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("BuscarPuntos", _args, callback, asyncState);
                return _result;
            }
            
            public Simit.GetPointsService.BuscarPuntosResponse EndBuscarPuntos(System.IAsyncResult result) {
                object[] _args = new object[0];
                Simit.GetPointsService.BuscarPuntosResponse _result = ((Simit.GetPointsService.BuscarPuntosResponse)(base.EndInvoke("BuscarPuntos", _args, result)));
                return _result;
            }
        }
    }
}
